/**
 * Shared response types for the Customer Intelligence engine.
 *
 * All money values are numbers (rupees), never formatted strings.
 * All percentages are decimal numbers (e.g. 42.5 means 42.5%), never strings.
 * A `null` percentage means "not computable" (e.g. no previous-period baseline)
 * and the UI renders it as "—". Growth is never Infinity/NaN.
 */

/** One cell in a retention cohort row (a single month-since-acquisition). */
export interface RetentionCohortCell {
	/** Months since acquisition (0 = acquisition month itself). */
	monthOffset: number;
	/** Calendar month for this cell, ISO "YYYY-MM". */
	month: string;
	/** Customers from the cohort active in this month. */
	activeCustomers: number;
	/** activeCustomers / cohortSize * 100, in [0, 100]. */
	retentionPct: number;
	/** Revenue from cohort customers in this month. */
	revenue: number;
	/** revenue / cohort month-0 revenue * 100 (null if no baseline). */
	revenuePct: number | null;
	/** Distinct bills from cohort customers in this month. */
	bills: number;
	/** revenue / bills (0 when no bills). */
	aov: number;
}

/** One acquisition cohort (row) in the retention grid. */
export interface RetentionCohortRow {
	/** Acquisition month, ISO "YYYY-MM". */
	cohortMonth: string;
	/** Distinct identified customers acquired this month (month-0 size). */
	cohortSize: number;
	/** Revenue generated by this cohort in its acquisition month. */
	cohortRevenue: number;
	/** Cells indexed by month offset (0..N). */
	cells: RetentionCohortCell[];
}

export interface RetentionCohortResult {
	/** Ordered acquisition-month rows (oldest first). */
	cohorts: RetentionCohortRow[];
	/** All month-offset columns present across cohorts, ascending. */
	monthOffsets: number[];
	/** Customers analysed (identified only; anonymous excluded). */
	identifiedCustomers: number;
}

/** A single revenue-composition segment card. */
export interface RevenueCompositionCard {
	key: "total" | "repeat" | "new" | "identified" | "anonymous";
	label: string;
	revenue: number;
	/** Share of total revenue in the current period (0..100). */
	revenuePct: number;
	customers: number;
	/** Share of total customers (0..100). */
	customerPct: number;
	bills: number;
	/** Share of total bills (0..100). */
	billsPct: number;
	/** revenue / bills (0 when no bills). */
	aov: number;
	/** Growth vs previous period, decimal % (null when no baseline). */
	revenueGrowthPct: number | null;
}

/** One equality assertion (e.g. Repeat + New == Total). */
export interface ReconciliationCheck {
	label: string;
	expected: number;
	actual: number;
	/** Absolute difference. */
	diffAbs: number;
	/** True when within tolerance (default ₹1). */
	ok: boolean;
}

export interface ReconciliationReport {
	ok: boolean;
	checks: ReconciliationCheck[];
	warnings: string[];
}

export interface RevenueCompositionResult {
	cards: RevenueCompositionCard[];
	/** Convenience totals for the current period. */
	totals: {
		revenue: number;
		customers: number;
		bills: number;
		aov: number;
	};
	/** Repeat+New==Total and Identified+Anonymous==Total assertions. */
	reconciliation: ReconciliationReport;
}

/** One lifetime visit-frequency bucket. */
export interface ValueDistributionRow {
	/** Bucket label, e.g. "1", "2", "5+". */
	bucket: string;
	/** Lower bound of visits for the bucket. */
	minVisits: number;
	/** True for the open-ended top bucket (e.g. 5+). */
	isOpenEnded: boolean;
	customers: number;
	revenue: number;
	bills: number;
	/** revenue / bills (0 when no bills). */
	aov: number;
	/** Lifetime value = revenue / customers (0 when no customers). */
	ltv: number;
	/** Share of total revenue (0..100). */
	revenueSharePct: number;
	/** Share of total customers (0..100). */
	customerSharePct: number;
	/** Average lifetime spend per customer (== ltv). */
	averageSpend: number;
}

export interface ValueDistributionResult {
	rows: ValueDistributionRow[];
	totals: {
		customers: number;
		revenue: number;
		bills: number;
	};
	/** Founder-facing interpretation strings generated in the business layer. */
	insights: string[];
	/** Sum(bucket revenue)==total and Sum(bucket customers)==total assertions. */
	reconciliation: ReconciliationReport;
}

/** Identity source of a resolved customer key. */
export type IdentitySource = "mobile" | "name" | "anonymous";

export interface IdentityConfidenceRow {
	source: IdentitySource;
	label: string;
	customers: number;
	customerPct: number;
	revenue: number;
	revenuePct: number;
	bills: number;
}

export interface IdentityConfidenceResult {
	rows: IdentityConfidenceRow[];
	totals: { customers: number; revenue: number; bills: number };
	/** Operational insight, e.g. "18% of revenue is anonymous — collect mobiles." */
	insight: string | null;
}

/** A Pareto concentration band (top X% of customers by revenue). */
export interface ConcentrationBand {
	label: string;
	/** Top percentile threshold, e.g. 10 for "Top 10%". */
	topPct: number;
	customers: number;
	revenue: number;
	revenueSharePct: number;
}

/** Revenue-at-Risk: dependence on the top-N highest-value customers. */
export interface RevenueAtRisk {
	topCustomerCount: number;
	revenue: number;
	revenueSharePct: number;
	/** How many of those top-N are identified (mobile/name). */
	identifiedCount: number;
}

export interface CustomerConcentrationResult {
	pareto: ConcentrationBand[];
	revenueAtRisk: RevenueAtRisk;
	totalCustomers: number;
	totalRevenue: number;
}

/** One weighted contributor to the Revenue Quality Score. */
export interface ScoreFactor {
	key: string;
	label: string;
	/** Underlying metric value (percentage, ratio, or rupees). Null if N/A. */
	value: number | null;
	/** 0..100 contribution score for this factor. */
	score: number;
	/** Weight (0..1) applied to `score`. */
	weight: number;
	note: string;
}

export type QualityBand = "Excellent" | "Healthy" | "Watch" | "Weak";

/** A "Why?" line behind the score — a positive driver or a drag. */
export interface ScoreReason {
	sign: "+" | "−";
	text: string;
}

export interface RevenueQualityScore {
	/** 0..100 composite score. */
	score: number;
	band: QualityBand;
	/** 1..5 star rating derived from the band. */
	stars: number;
	headline: string;
	factors: ScoreFactor[];
	/** Explainability — the drivers behind the score (no black box). */
	reasons: ScoreReason[];
	/** Key metrics surfaced on the health card. */
	metrics: {
		repeatRevenuePct: number;
		newRevenuePct: number;
		month1RetentionPct: number | null;
		anonymousRevenuePct: number;
		aov: number;
		ltv: number;
	};
}

export type InsightTone = "positive" | "warning" | "critical" | "neutral";

export interface CustomerInsight {
	id: string;
	title: string;
	detail: string;
	tone: InsightTone;
}

/** Priority level for a founder action (red = act now, green = good news). */
export type PriorityLevel = "high" | "medium" | "good";

/** One founder-facing action item — "what deserves attention today". */
export interface FounderPriority {
	id: string;
	level: PriorityLevel;
	title: string;
	detail: string;
	/** Team that owns the action (Marketing, Category, Operations…). */
	owner: string;
	/** Optional quantified stake (e.g. "₹1.8L at risk"). */
	metric?: string;
}

/** The 5-second identity card of the business. */
export interface CustomerSnapshot {
	customers: number;
	health: { score: number; band: QualityBand; stars: number };
	repeatRevenuePct: number;
	newRevenuePct: number;
	month1RetentionPct: number | null;
	anonymousRevenuePct: number;
	ltv: number;
	aov: number;
	vipRevenuePct: number;
	revenueAtRiskPct: number;
}

export interface CustomerIntelligenceData {
	filters: import("@/lib/founder/types").DashboardFilters;
	periods: import("@/lib/business-logic/comparison").ComparisonPeriods;
	comparisonLabel: string;
	retentionCohort: RetentionCohortResult;
	revenueComposition: RevenueCompositionResult;
	valueDistribution: ValueDistributionResult;
	identityConfidence: IdentityConfidenceResult;
	concentration: CustomerConcentrationResult;
	qualityScore: RevenueQualityScore;
	insights: CustomerInsight[];
	snapshot: CustomerSnapshot;
	priorities: FounderPriority[];
	/** Combined reconciliation across all engines. */
	reconciliation: ReconciliationReport;
}

export interface CustomerIntelligenceResponse {
	success: boolean;
	data?: CustomerIntelligenceData;
	error?: string;
}
